##### THIS ALLOWS US TO DEPLOY THE SITE FROM A GIT REPO ######
---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/cfsb84569643/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp red_dots.html $DEPLOYPATH
    - /bin/cp car_vs_cones.html $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH