##### THIS ALLOWS US TO DEPLOY THE SITE FROM A GIT REPO ######
---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/cfsb84569643/repositories/cfsb/
    - / -R .vscode $DEPLOYPATH
    - / -R assets $DEPLOYPATH
    - / -R css $DEPLOYPATH
    - / -R fonts $DEPLOYPATH
    - / -R img $DEPLOYPATH
    - / -R js $DEPLOYPATH
    / index.html $DEPLOYPATH